services:
  - type: web
    name: next-level-vault
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: PORT
        value: 8080
      - key: RENDER_EXTERNAL_URL
        value: https://next-level-vault.onrender.com
