services:
  - type: web
    name: next-level-vault
    runtime: docker          # <--- Yahan python ki jagah docker likha hai
    plan: free

    envVars:
      - key: API_ID
        sync: false

      - key: API_HASH
        sync: false

      - key: BOT_TOKEN
        sync: false

      - key: OWNER_ID
        sync: false

      - key: MONGO_URL
        sync: false

      - key: DB_NAME
        value: stark_bot

      - key: ADMIN_IDS
        value: ""

      - key: FORCE_JOIN_CHAT_IDS
        value: ""

      - key: PORT
        value: 8080
